### ISSUE TITLE
motorengine/mongoengine middleware?

### ISSUE THREAD

**Issue by auvipy** [dailymuse/oz#2]
is it possible to add this type feature to work with mongo? if how to add?

**Comment by ysimonson** [comment]
Yes. The redis plugin has the simplest example of similar functionality: https://github.com/dailymuse/oz/tree/master/oz/redis

You can also consult the readme, which also outlines similar functionality.

**Comment by auvipy** [comment]
writing modules or using 3rd party apps? or extneding the framework?

**Comment by ysimonson** [comment]
You'd use whatever mongodb library you're interested in, and wire it into oz as a plugin.
